version: "3"

services:
  setup:
    image: busybox
    volumes:
      - ./kaggle:/kaggle
    command: tar -C kaggle/ -zxvf kaggle/stage_2_train.csv.tar.gz

  server:
    build: src/
    restart: always
    volumes:
      - ./examples:/app/examples
      - ./kaggle:/kaggle
    command: python core.py
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    depends_on:
      - setup
