version: "3"

services:
  server:
    build: src/
    restart: always
    volumes:
      - ./examples:/app/examples
      - ./kaggle:/kaggle
    command: python core.py
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
